"""Public package exports for the Bloch-wave dynamicality analyser."""

from .bloch import (
    StructureMatrixResult,
    beam_intensities,
    build_structure_matrix,
    extinction_distance_angstrom,
    propagate_bloch_wave,
)
from .geometry import (
    RotationSeriesOrientationModel,
    ZoneAxisMatch,
    build_zone_axes,
    cell_volume,
    excitation_error,
    generate_candidate_reflections,
    nearest_zone_axis,
    project_to_detector,
    rodrigues_rotation_matrix,
)
from .metrics import (
    aggregate_frame_thickness_sensitivity,
    aggregate_reflection_thickness_sensitivity,
    combined_proxy_score,
    effective_coupling_multiplicity,
    thickness_sensitivity_metrics,
    two_beam_metric,
)
from .parsers import (
    CompositionEntry,
    CompositionResult,
    GXPARMData,
    IntegrateData,
    UnitCell,
    XDSInputData,
    parse_composition,
    parse_gxparm,
    parse_gxparm_text,
    parse_integrate_hkl,
    parse_integrate_text,
    parse_xds_inp,
    parse_xds_inp_text,
)
from .pipeline import AnalysisConfig, AnalysisResult, run_analysis, run_analysis_from_paths
from .visualization import plot_detector_frame, plot_frame_summary, plot_thickness_scan
from .wilson import WilsonCalibration, merge_equivalent_reflections, symmetry_key, wilson_calibrate

__all__ = [
    "AnalysisConfig",
    "AnalysisResult",
    "CompositionEntry",
    "CompositionResult",
    "GXPARMData",
    "IntegrateData",
    "RotationSeriesOrientationModel",
    "StructureMatrixResult",
    "UnitCell",
    "WilsonCalibration",
    "XDSInputData",
    "ZoneAxisMatch",
    "aggregate_frame_thickness_sensitivity",
    "aggregate_reflection_thickness_sensitivity",
    "beam_intensities",
    "build_structure_matrix",
    "build_zone_axes",
    "cell_volume",
    "combined_proxy_score",
    "effective_coupling_multiplicity",
    "excitation_error",
    "extinction_distance_angstrom",
    "generate_candidate_reflections",
    "merge_equivalent_reflections",
    "nearest_zone_axis",
    "parse_composition",
    "parse_gxparm",
    "parse_gxparm_text",
    "parse_integrate_hkl",
    "parse_integrate_text",
    "parse_xds_inp",
    "parse_xds_inp_text",
    "plot_detector_frame",
    "plot_frame_summary",
    "plot_thickness_scan",
    "project_to_detector",
    "propagate_bloch_wave",
    "rodrigues_rotation_matrix",
    "run_analysis",
    "run_analysis_from_paths",
    "symmetry_key",
    "thickness_sensitivity_metrics",
    "two_beam_metric",
    "wilson_calibrate",
]
