"""Public package exports for the Bloch-wave dynamicality analyser."""

from .bloch import (
    StructureMatrixResult,
    beam_intensities,
    build_structure_matrix,
    extinction_distance_angstrom,
    propagate_bloch_wave,
)
from .geometry import (
    RotationSeriesOrientationModel,
    ReciprocalMatrixOrientationModel,
    ZoneAxisMatch,
    build_zone_axes,
    cell_volume,
    excitation_error,
    generate_candidate_reflections,
    nearest_zone_axis,
    project_to_detector,
    reciprocal_lookup_from_table,
    rodrigues_rotation_matrix,
)
from .html_visualization import export_orientation_peaks_html
from .html_visualization import export_single_frame_gaussian_html
from .metrics import (
    aggregate_frame_thickness_sensitivity,
    aggregate_reflection_thickness_sensitivity,
    combined_proxy_score,
    effective_coupling_multiplicity,
    orientation_excitation_probability,
    orientation_proxy_score,
    orientation_sg_gradient,
    orientation_sg_sigma,
    thickness_sensitivity_metrics,
    two_beam_metric,
)
from .dynamical_uncertainty import (
    CanonicalObservationData,
    DynamicalUncertaintyConfig,
    DynamicalUncertaintyResult,
    canonical_observations_from_stream,
    canonical_observations_from_xds,
    run_dynamical_uncertainty_from_stream,
    run_dynamical_uncertainty_from_xds,
    run_dynamical_uncertainty_pipeline,
)
from .parsers import (
    CompositionEntry,
    CompositionResult,
    CrystFELStreamData,
    GXPARMData,
    IntegrateData,
    UnitCell,
    XDSInputData,
    crystfel_stream_to_analysis_inputs,
    parse_composition,
    parse_crystfel_stream,
    parse_crystfel_stream_text,
    parse_gxparm,
    parse_gxparm_text,
    parse_integrate_hkl,
    parse_integrate_text,
    parse_xds_inp,
    parse_xds_inp_text,
)
from .pets2 import PETSFrameState, PETSModel, load_pets_model, pets_model_to_analysis_inputs, predict_pets_detector_spots
from .pipeline import (
    AnalysisConfig,
    AnalysisResult,
    run_analysis,
    run_analysis_from_pets_project_path,
    run_analysis_from_paths,
    run_analysis_from_stream_path,
)
from .visualization import plot_detector_frame, plot_frame_summary, plot_thickness_scan
from .wilson import WilsonCalibration, merge_equivalent_reflections, symmetry_key, wilson_calibrate

__all__ = [
    "AnalysisConfig",
    "AnalysisResult",
    "CompositionEntry",
    "CompositionResult",
    "CanonicalObservationData",
    "CrystFELStreamData",
    "DynamicalUncertaintyConfig",
    "DynamicalUncertaintyResult",
    "GXPARMData",
    "IntegrateData",
    "PETSFrameState",
    "PETSModel",
    "ReciprocalMatrixOrientationModel",
    "RotationSeriesOrientationModel",
    "StructureMatrixResult",
    "UnitCell",
    "WilsonCalibration",
    "XDSInputData",
    "ZoneAxisMatch",
    "aggregate_frame_thickness_sensitivity",
    "aggregate_reflection_thickness_sensitivity",
    "beam_intensities",
    "build_structure_matrix",
    "canonical_observations_from_stream",
    "canonical_observations_from_xds",
    "build_zone_axes",
    "cell_volume",
    "combined_proxy_score",
    "effective_coupling_multiplicity",
    "export_orientation_peaks_html",
    "export_single_frame_gaussian_html",
    "excitation_error",
    "extinction_distance_angstrom",
    "generate_candidate_reflections",
    "merge_equivalent_reflections",
    "nearest_zone_axis",
    "orientation_excitation_probability",
    "orientation_proxy_score",
    "orientation_sg_gradient",
    "orientation_sg_sigma",
    "parse_composition",
    "parse_crystfel_stream",
    "parse_crystfel_stream_text",
    "parse_gxparm",
    "parse_gxparm_text",
    "parse_integrate_hkl",
    "parse_integrate_text",
    "parse_xds_inp",
    "parse_xds_inp_text",
    "load_pets_model",
    "pets_model_to_analysis_inputs",
    "predict_pets_detector_spots",
    "plot_detector_frame",
    "plot_frame_summary",
    "plot_thickness_scan",
    "project_to_detector",
    "reciprocal_lookup_from_table",
    "crystfel_stream_to_analysis_inputs",
    "propagate_bloch_wave",
    "run_dynamical_uncertainty_from_stream",
    "run_dynamical_uncertainty_from_xds",
    "run_dynamical_uncertainty_pipeline",
    "rodrigues_rotation_matrix",
    "run_analysis",
    "run_analysis_from_pets_project_path",
    "run_analysis_from_paths",
    "run_analysis_from_stream_path",
    "symmetry_key",
    "thickness_sensitivity_metrics",
    "two_beam_metric",
    "wilson_calibrate",
]
